P5 9/Dining room page
team-prstmw/P5FE pull request #5
Opened 2022-05-15 13:59 UTC by MCaliJr

Initial setup for dining room page

2022-05-15 13:59 UTC, MCaliJr commented
The overall form is what I imagine we may want to use in the final product.
Needs styling + logic.

2022-05-23 18:02 UTC, ruljin requested changes

2022-05-23 18:02 UTC, ruljin commented on package.json
>      "typecheck": "tsc --noEmit"
I recommend using so-called `conventional commits`

https://www.conventionalcommits.org/en/v1.0.0/

2022-05-23 18:02 UTC, ruljin commented on src/App.tsx
> +import DiningRoomPage from './pages/DiningRoomPage/DiningRoomPage';
I recommend using `named exports`

2022-05-23 18:02 UTC, ruljin commented on src/App.tsx
> +import { ReactElement } from 'react';
App doesn't need `ReactElement`. It will be allright if you will write it as `function App() { ... }` without using that `ReactElement`.

2022-05-23 18:02 UTC, ruljin commented on src/components/DiningRoomModal/DiningRoomModal.css
> +Button {
Never style by `tags` if the app isn't very small. It is a matter of time before it will hit you with a ricochet

2022-05-23 18:02 UTC, ruljin commented on src/components/DiningRoomModal/DiningRoomModal.css
> +.diningRoomModal__modal {
I see that you guys don't use `sass` (but you have it in your project) or even `CSS modules`. In that way, use `BEM Methodology` and it is not even similar to it.

http://getbem.com/

2022-05-23 18:02 UTC, ruljin commented on src/components/DiningRoomModal/DiningRoomModal.css
> +.margin-bottom {
One time you are using `atoms` and later something that was supposed to be like `BEM`. Choose one and use it

2022-05-23 18:02 UTC, ruljin commented on src/components/DiningRoomModal/DiningRoomModal.css
> +@media (max-width: 50rem) {
I'm not sure if `media queries` with `rem` are a good idea

https://medium.com/@barrypeng6/why-should-not-use-rem-unit-in-media-query-5645d0163ce5

2022-05-23 18:02 UTC, ruljin commented on src/components/DiningRoomTable/DiningRoomTable.css
> +:root {
The `root` should be moved to `variables.css` on top level of the app and should have the `css variables` in it. Later, that file should be imported to the other `css` files that need to use anything out of it.

2022-05-23 18:02 UTC, ruljin commented on src/components/DiningRoomTable/DiningRoomTable.tsx
> +const tableStatuses = {
Use `SCREAMING_SNAKE_CASE`

https://jamie.build/const

2022-05-23 18:02 UTC, ruljin commented on src/components/DiningRoomTable/DiningRoomTable.tsx
> +import DiningRoomModal from '../DiningRoomModal/DiningRoomModal';
I recommend using `named exports`

2022-05-23 18:02 UTC, ruljin commented on src/components/DiningRoomTable/DiningRoomTable.tsx
> +  }
You could move the whole component logic to the `custom hook` called e.g `useDiningRoomTable` and return in it only what you need to use in the component

2022-05-23 18:02 UTC, ruljin commented on src/components/DiningRoomTable/DiningRoomTable.tsx
> +              <TableCell style={{ color: 'white', fontWeight: '600' }}>Table number</TableCell>
If there is no reason for it then stay with one way of styling elements. Use `sx` or `css` file with proper classes and use them

2022-05-23 18:02 UTC, ruljin commented on src/pages/DiningRoomPage/DiningRoomPage.tsx
> +import DiningRoomTable from 'src/components/DiningRoomTable/DiningRoomTable';
☝️

2022-05-23 18:02 UTC, ruljin commented on src/pages/DiningRoomPage/DiningRoomPage.css
> +.DiningRoomPage__title {
☝️

2022-05-23 18:02 UTC, ruljin commented on src/pages/DiningRoomPage/DiningRoomPage.css
> +.DiningRoomPage {
☝️

2022-05-23 20:07 UTC, FilipHalon commented on src/components/DiningRoomTable/DiningRoomTable.css
> +:root {
You might consider adding the `.module.` part to the names of the css files you created to make the naming consistent with the rest of the code created so far.

2022-05-24 20:09 UTC, ruljin commented on src/components/DiningRoomModal/DiningRoomModal.css
> +.diningRoomModal__margin-bottom {
`BEM` is using double `--` for `modifiers`

2022-05-25 10:00 UTC, merged